package com.lean.lean.enums;

public enum PaymentIntentStatus {
    CREDENTIALS_UPDATE_REQUIRED("CREDENTIALS_UPDATE_REQUIRED"),
    AWAITING_END_USER_AUTHORIZATION("AWAITING_END_USER_AUTHORIZATION"),
    AWAITING_LOGIN_MFA_TOKEN("AWAITING_LOGIN_MFA_TOKEN"),
    AWAITING_APP_AUTH("AWAITING_APP_AUTH"),
    AWAITING_PAYMENT_MFA_TOKEN("AWAITING_PAYMENT_MFA_TOKEN"),
    AWAITING_PAYMENT_SECURITY_QUESTIONS("AWAITING_PAYMENT_SECURITY_QUESTIONS"),
    INVALID_CREDENTIALS("INVALID_CREDENTIALS"),
    INVALID_LOGIN_MFA("INVALID_LOGIN_MFA"),
    INVALID_PAYMENT_MFA("INVALID_PAYMENT_MFA"),
    BENEFICIARY_NOT_FOUND("BENEFICIARY_NOT_FOUND"),
    MFA_ATTEMPTS_EXHAUSTED("MFA_ATTEMPTS_EXHAUSTED"),
    SECURITY_QUESTION_ANSWER_ATTEMPTS_EXHAUSTED("SECURITY_QUESTION_ANSWER_ATTEMPTS_EXHAUSTED"),
    PENDING_WITH_BANK("PENDING_WITH_BANK"),
    AWAITING_AUTHORIZATION("AWAITING_AUTHORIZATION"),
    FAILED("FAILED"),
    AWAITING_AUTHORIZATION_LOGIN_MFA("AWAITING_AUTHORIZATION_LOGIN_MFA"),
    INVALID_AUTHORIZATION_LOGIN_MFA("INVALID_AUTHORIZATION_LOGIN_MFA"),
    AWAITING_AUTHORIZATION_LOGIN_SECURITY_QUESTION("AWAITING_AUTHORIZATION_LOGIN_SECURITY_QUESTION"),
    AWAITING_AUTHORIZATION_LOGIN_SECURITY_QUESTION_ANSWER("AWAITING_AUTHORIZATION_LOGIN_SECURITY_QUESTION_ANSWER"),
    INVALID_AUTHORIZATION_LOGIN_SECURITY_QUESTION_ANSWER("INVALID_AUTHORIZATION_LOGIN_SECURITY_QUESTION_ANSWER"),
    AUTHORIZATION_LOGIN_SECURITY_QUESTION_ANSWER_ATTEMPTS_EXHAUSTED("AUTHORIZATION_LOGIN_SECURITY_QUESTION_ANSWER_ATTEMPTS_EXHAUSTED"),
    AUTHORIZATION_FAILED("AUTHORIZATION_FAILED"),
    AWAITING_AUTHORIZATION_PAYMENT_MFA("AWAITING_AUTHORIZATION_PAYMENT_MFA"),
    INVALID_AUTHORIZATION_PAYMENT_MFA("INVALID_AUTHORIZATION_PAYMENT_MFA"),
    PARTIAL_ACCEPTED_BY_BANK("PARTIAL_ACCEPTED_BY_BANK"),
    AUTHORIZATION_MFA_ATTEMPTS_EXHAUSTED("AUTHORIZATION_MFA_ATTEMPTS_EXHAUSTED");

    private final String value;

    PaymentIntentStatus(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public static PaymentIntentStatus fromValue(String value) {
        for (PaymentIntentStatus status : values()) {
            if (status.value.equalsIgnoreCase(value)) {
                return status;
            }
        }
        throw new IllegalArgumentException("Unknown payment intent status: " + value);
    }
}
